### ISSUE TITLE
Content Offset outdated

### ISSUE THREAD

**Issue by AlexanderC** [MitocGroup/adtechmedia-wordpress-plugin#236]
Steps to reproduce:
1. Install Plugin
2. Go to AdTechMedia plugin page
3. Set "Content preview" to 2 paragraphs
4. Open article Page in a new tab
5. Set "Content preview" to 1 paragraph
6. Open article Page in a new tab

*Expected:* Content preview 1 paragraph and other scrambled and blurred
*Actual:*  Content preview 2 paragraph but the second is scrambled but not blurred 

<img width="1440" alt="screen shot 2017-09-06 at 14 19 08" src="https://user-images.githubusercontent.com/1415757/30109397-d35d5bb6-930e-11e7-83d3-529f591bffa2.png">

**Comment by AlexanderC** [comment]
atm.min.js settings are outdated (offset=2) but on WP are ok (offset=1 in DB and API call)

**Comment by AlexanderC** [comment]
Bug disappears when saving the configuration second time

**Comment by AlexanderC** [comment]
Logs:
```
    [body] => {"errorMessage":"{\"errorType\":\"UnknownError\",\"errorMessage\":\"RequestId: f120bf16-92f4-11e7-aa49-1df90c90fddb Process exited before completing request\",\"errorStack\":\"Error: Unknown error occurred.\\n    at Function._decodeRawErrorObject (/var/task/bootstrap.js:29919:23)\\n    at LambdaResponse._decodePayload (/var/task/bootstrap.js:29895:43)\\n    at new LambdaResponse (/var/task/bootstrap.js:29798:32)\\n    at Response.<anonymous> (/var/task/bootstrap.js:58481:28)\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:364:18)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)\\n    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\\n    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\\n    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)\\n    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\\n    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\\n    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)\\n    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\\n    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\\n    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)\\n    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\\n    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\\n    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)\\n    at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:95:12)\\n    at IncomingMessage.onEnd (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:269:13)\\n    at emitNone (events.js:91:20)\\n    at IncomingMessage.emit (events.js:185:7)\\n    at endReadableNT (_stream_readable.js:974:12)\\n    at /var/task/bootstrap.js:80457:31\\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\\n    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:128:9)\",\"_deep_error_code_\":400}"}
    [response] => Array
        (
            [code] => 400
            [message] => Bad Request
        )
```

**Comment by AlexanderC** [comment]
Failing in `DeepTestPropertyGenerateJs068e4ac0d1d` somewhere between `this._readFileGunzipMaybe('atm-build/atm.min.js')` and `this._writeAndGzipIfNotLocal(outputJsFilePath, jsDistributionContent)` code blocks

**Comment by AlexanderC** [comment]
Failing in `this._gzipBuffer(content, (error, compressedContent)` in `DeepTestPropertyGenerateJs068e4ac0d1d `

**Comment by AlexanderC** [comment]
It might be related to https://github.com/devdazed/gzip-buffer/blob/master/lib/gzip-buffer.js#L57, there's no `stream.on('end')` listener set

**Comment by avozicov** [comment]
Test **Passed**
Paragraph config are successfully saved and applied to content
<img width="477" alt="screen shot 2017-09-07 at 15 57 46" src="https://user-images.githubusercontent.com/12330493/30164472-51cc31a8-93e5-11e7-8425-0a10bf444434.png">
<img width="1280" alt="screen shot 2017-09-07 at 15 56 49" src="https://user-images.githubusercontent.com/12330493/30164471-51cbbe30-93e5-11e7-97bd-4049622b7470.png">
